### ISSUE TITLE
code use

### ISSUE THREAD

**Issue by Moi-nune** [Bonkeyzz/opencv_poketwofinder#1]
can the code be used to make a discord bot 
and im talking abt a bot not a self bot
and if so can you please like kind of guide me through that pls since im kind of a newb
ty

**Comment by Moi-nune** [comment]
also im not clear as to where the put the token in the code wheter self or bot

**Comment by Bonkeyzz** [comment]
This is not a bot, its just an openCV project.
You may use this to make a discord bot, at your own risk though. I'm not responsible if poketwo and/or discord bans you.
